### ISSUE TITLE
Similar github actions?

### ISSUE THREAD

**Issue by nyandika** [SpaceyaTech/Team-Rio-Django#107]
Looking at [this action](https://github.com/SpaceyaTech/Team-Rio-Django/blob/main/.github/workflows/django-postgres-ci.yml) and [this one](https://github.com/SpaceyaTech/Team-Rio-Django/blob/main/.github/workflows/django.yml) it seems to me they are running essentially the same steps. 
Wondering if there is a reason why we have two of them

**Comment by JimmyTron** [comment]
** Have been working on this pull request that has the change already. **
The two are similar but were intended to work on different aspects of the project. 

have updated the refs that fix it

![Screenshot from 2023-03-10 13-24-13](https://user-images.githubusercontent.com/23496280/224295843-fe7e1732-07b8-47a7-a726-7623bd41c82f.png)
