### ISSUE TITLE
Project skeleton 

### ISSUE THREAD

**Issue by JimmyTron** [SpaceyaTech/Team-Rio-Django#17]
## Hi there, 
<sup> @sangkips once the ```environment settings``` issue is resoled by @wanjirumurira and @mamu234  </sup>
> pull the changes and create an empty project. 

> Create a new branch and push it upstream.

* Don't forget to open a pull request 😉

**Comment by mamu234** [comment]
Ok

**Comment by sangkips** [comment]
Can I go ahead?
