### ISSUE TITLE
Update the .gitignore file

### ISSUE THREAD

**Issue by JimmyTron** [SpaceyaTech/Team-Rio-Django#23]
Add a .gitignore file
The __pycache__ folder contains compiled binaries that should be ignored

_Originally posted by @nyandika in https://github.com/SpaceyaTech/Team-Rio-Django/pull/19#pullrequestreview-1163606827_

**Comment by Fredrick-Waihenya** [comment]
I"ll work on it.

**Comment by nyandika** [comment]
Please dont close the issue until the actual work has been done to automatically close it. helps tracking bits done and those pending

**Comment by JimmyTron** [comment]
The issues here will automatically get closed once a pull request tackling them is successfully merged.
