### ISSUE TITLE
Handling Images

### ISSUE THREAD

**Issue by hellen-22** [SpaceyaTech/Team-Rio-Django#36]
[Pillow](https://pypi.org/project/Pillow/) is an image library that we shall use to manipulate our images.
We need to tell Django which URL to use for serving the media files and also specify the root directory where our images will be stored.

**Comment by sangkips** [comment]
Can we have a default avatar so that incase the user doesn't want to provide a picture then we could have a placeholder and also can we specify where we can store images.
