### ISSUE TITLE
Handling phone number fields 

### ISSUE THREAD

**Issue by sangkips** [SpaceyaTech/Team-Rio-Django#38]
Find a better way to have phone numbers handle international phone number formats such as +1 777777. This way it will be better to handle users' phone numbers globally.

**Comment by JimmyTron** [comment]
Any progress on this issue @sangkips what are the options you have?

**Comment by sangkips** [comment]
> Any progress on this issue @sangkips what are the options you have?

I will work on this probably today, I have been busy
