### ISSUE TITLE
Transfer all tests to a tests module (REOPENED)

### ISSUE THREAD

**Issue by JimmyTron** [SpaceyaTech/Team-Rio-Django#43]
What if we had all our tests in one place insteadvof having them on idividual apps? 
 What would be the merits of demerits of doing so?

_Originally posted by @JimmyTron in https://github.com/SpaceyaTech/Team-Rio-Django/pull/40#issuecomment-1321812723_

**Comment by hellen-22** [comment]
Like one file or?

**Comment by Eugene-Kwaka** [comment]
In the django documentation it says when the application scales and the test scales too, it is recommended to place the tests in packages such as test_models.py, test_forms.py and test_views.py. Maybe we can create a folder for the tests instead of a separate test app?
