### ISSUE TITLE
Authentication Implementation

### ISSUE THREAD

**Issue by JimmyTron** [SpaceyaTech/Team-Rio-Django#47]
using non-native auth services to authenticate users to the application.

The authentication service makes sure that information is accessed only by users who have the access permission or right. The SpaceYaTech OpenSource CMS implements two forms of Authentication - JWT Authentication and Oauth 2.0 for Authentication and Authorization of Users within the Application. Here is a detailed look into the potential implementation of both forms of Authentication forms: 
Read more here ![Authentication services](https://github.com/SpaceyaTech/CMS-Backend-Repository/wiki/Technical-Description-Of-Product#authentication-service)

**Comment by teslima0** [comment]
Hi, I'm interested in solving the issue

**Comment by JimmyTron** [comment]
@Msdot001 @teslima0 any progress on this? would like to see how you are handling it

**Comment by teslima0** [comment]
work in progress, being able to certain thing and looking forward to  complete the task as soon as possible

**Comment by Msdot001** [comment]
Yes,  I should be able to merge my work into the development branch this night. Trying to finalize the task

**Comment by JimmyTron** [comment]
dont ,erge the dev branch just do it to the main branch


> Yes, I should be able to merge my work into the development branch this night. Trying to finalize the task

@teslima0

**Comment by sangkips** [comment]
Just do small tasks as you commit so that it will be much easier doing the reviews. I saw you had pushed so much code. It will also become easy for others to internalize what you have created.

**Comment by Msdot001** [comment]
Noted
